services:
  app:
    container_name: rui-cmd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    volumes:
      - .:/app       # 将本地代码挂载到容器中，方便开发时实时更新
      - /opt/voices:/opt/voices
    environment:
      - TEST=true  # 示例环境变量，可根据需要调整
    networks:
      - my-shared-network


networks:
  my-shared-network:
    external: true