version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    volumes:
      - .:/app       # 将本地代码挂载到容器中，方便开发时实时更新
    environment:
      - TEST=true  # 示例环境变量，可根据需要调整