services:
  app:
    container_name: rui-cmd
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "127.0.0.1:8101:8101"
    volumes:
      - .:/app       # 将本地代码挂载到容器中，方便开发时实时更新
      - /opt/voices:/opt/voices
      - /fortune:/fortune
    environment:
      - TZ=Asia/Shanghai
    networks:
      - 1panel-network


networks:
  1panel-network:
    external: true