services:
  app:
    container_name: rui-cmd
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    volumes:
      - .:/app       # 将本地代码挂载到容器中，方便开发时实时更新
      - /opt/voices:/opt/voices
    environment:
      - TZ=Asia/Shanghai
    networks:
      - 1panel-network
      - external


networks:
  1panel-network:
    external: true
  maim_bot:
    external: true